services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5252"